export const DUMMY_BUILDS = [
  {
    id: 'dummy-1',
    title: 'Glass Cannon Haze',
    createdAt: '2026-04-15T14:30:00Z',
    author: { name: 'ProGamer' },
    votes: 342,
    hero: { id: 17, name: 'Haze', images: { portrait: '' } },
    totalCost: 24500,
    items: [
      { id: 'd1i1', name: 'Monster Rounds',  cost: 500,  slot: 'weapon',   tier: 1, images: { icon: '' } },
      { id: 'd1i2', name: 'Active Reload',   cost: 1250, slot: 'weapon',   tier: 2, images: { icon: '' } },
      { id: 'd1i3', name: 'Hollow Point',    cost: 3200, slot: 'weapon',   tier: 3, images: { icon: '' } },
      { id: 'd1i4', name: 'Burst Fire',      cost: 3000, slot: 'weapon',   tier: 3, images: { icon: '' } },
      { id: 'd1i5', name: 'Glass Cannon',    cost: 6300, slot: 'weapon',   tier: 4, images: { icon: '' } },
      { id: 'd1i6', name: 'Warp Stone',      cost: 3000, slot: 'vitality', tier: 3, images: { icon: '' } },
    ],
    guide: {
      early: "Start with Monster Rounds + Active Reload. Focus on last-hitting and denying enemies. Haze's passive scales with weapon damage so small early leads snowball hard. Harass with Smoke Bomb and back off safely.",
      mid:   'Rush Hollow Point into Burst Fire. Look for flanks during teamfights — Bullet Dance after Sleep Dagger will wipe squishies in one rotation. Take every 1v1 you can win.',
      late:  'Complete Glass Cannon last. Position behind your team and use Fixation stacks to melt tanks. One full clip should delete most heroes. Never go in first.',
    },
    video: null,
  },
  {
    id: 'dummy-2',
    title: 'Unkillable Abrams',
    createdAt: '2026-04-18T09:00:00Z',
    author: { name: 'TankKing' },
    votes: 218,
    hero: { id: 1, name: 'Abrams', images: { portrait: '' } },
    totalCost: 19800,
    items: [
      { id: 'd2i1', name: 'Extra Health',   cost: 500,  slot: 'vitality', tier: 1, images: { icon: '' } },
      { id: 'd2i2', name: 'Bullet Armor',   cost: 1250, slot: 'vitality', tier: 2, images: { icon: '' } },
      { id: 'd2i3', name: 'Spirit Armor',   cost: 1250, slot: 'vitality', tier: 2, images: { icon: '' } },
      { id: 'd2i4', name: 'Lifestrike',     cost: 3000, slot: 'vitality', tier: 3, images: { icon: '' } },
      { id: 'd2i5', name: 'Colossus',       cost: 6300, slot: 'vitality', tier: 4, images: { icon: '' } },
      { id: 'd2i6', name: 'Leech',          cost: 6300, slot: 'vitality', tier: 4, images: { icon: '' } },
    ],
    guide: {
      early: 'Buy Extra Health into Bullet Armor. Your job is to soak damage and create space for carries. Siphon Life every trade to keep HP topped up. Contest every zip-line and deny creeps.',
      mid:   'Complete Lifestrike for fight sustain. Dive backlines with Shoulder Charge → Seismic Impact and let your team follow. Stay in the middle of every fight — you cannot be killed.',
      late:  'Colossus + Leech makes you virtually unkillable in extended fights. Activate both during big teamfights. You should be taking 2–3 enemies at once while your carries clean up.',
    },
    video: null,
  },
  {
    id: 'dummy-3',
    title: 'One-Shot Vindicta',
    createdAt: '2026-04-22T16:45:00Z',
    author: { name: 'SniperElite' },
    votes: 501,
    hero: { id: 11, name: 'Vindicta', images: { portrait: '' } },
    totalCost: 28100,
    items: [
      { id: 'd3i1', name: 'Mystic Shot',     cost: 1250, slot: 'weapon', tier: 2, images: { icon: '' } },
      { id: 'd3i2', name: 'Slowing Bullets', cost: 1250, slot: 'weapon', tier: 2, images: { icon: '' } },
      { id: 'd3i3', name: "Hunter's Aura",   cost: 3000, slot: 'weapon', tier: 3, images: { icon: '' } },
      { id: 'd3i4', name: 'Ricochet',        cost: 6300, slot: 'weapon', tier: 4, images: { icon: '' } },
      { id: 'd3i5', name: 'Lucky Shot',      cost: 6300, slot: 'weapon', tier: 4, images: { icon: '' } },
      { id: 'd3i6', name: 'Surge of Power',  cost: 3000, slot: 'spirit', tier: 3, images: { icon: '' } },
    ],
    guide: {
      early: 'Stake is your primary tool. Bind enemies and poke from high ground at every opportunity. Mystic Shot + Slowing Bullets let you kite endlessly — never fight at the same level as your target.',
      mid:   "Hunter's Aura amplifies your burst combo significantly. Pick off isolated targets: Stake → Crow's Demise → follow-up shots. Rotate between lanes using your Flight to apply map pressure.",
      late:  'Lucky Shot + Ricochet turns you into a one-shot machine at range. Stay permanently elevated. Use Flight defensively when dived. A fully-stacked Vindicta at this point wins every duel.',
    },
    video: {
      id: 'dQw4w9WgXcQ',
      title: 'Vindicta One-Shot Guide — Season 1',
      channel: 'DeadlockPro',
      thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
      timestamps: [
        { time: '0:30', seconds: 30,  label: 'Early laning',         color: 'bg-green-500/20 border-green-500/50 text-green-300' },
        { time: '2:15', seconds: 135, label: 'First kill combo',     color: 'bg-amber-500/20 border-amber-500/50 text-amber-300' },
        { time: '5:00', seconds: 300, label: 'Mid game rotations',   color: 'bg-teal-500/20 border-teal-500/50 text-teal-300' },
        { time: '8:40', seconds: 520, label: 'Team fight positioning', color: 'bg-purple-500/20 border-purple-500/50 text-purple-300' },
      ],
    },
  },
];

export const DUMMY_MAP = Object.fromEntries(DUMMY_BUILDS.map(b => [b.id, b]));
